

name: 'np_dbt_snowflake'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# dbt models under customer_rev
models:
  np-dbt-snowflake:
    customer_rev:
      orders_stg:
        +schema: L1_STAGE
        +materialized: view
      customers_stg:
        +schema: 'L1_STAGE'
        +materialized: view
      orderitems_stg:
        +schema: 'L1_STAGE'
        +materialized: view
      employees_stg:
        +schema: 'L1_STAGE'
        +materialized: view
      orders_fact:
        +schema: 'L1_FACTS'
        +materialized: table
      customerrevenue:
        +schema: 'L1_REPORTING'
        +materialized: table